version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/frontend'
      - '/tests'
      - '/email-templates'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'gomod'
    directories:
      - '/backend'
      - '/cli'
      - '/types'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'github-actions'
    directories:
      - '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directories:
      - '/docker'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'devcontainers'
    directories:
      - '/'
    schedule:
      interval: 'weekly'
